#!/usr/bin/env python3
"""
AWS Configuration Setup Script
Helps configure credentials and validate AWS connectivity for the healthcare pipeline
"""

import os
import sys
from pathlib import Path
import boto3
from dotenv import load_dotenv, find_dotenv

def setup_credentials_from_user():
    """Interactively collect AWS credentials from user"""
    print("\n" + "="*60)
    print("AWS Healthcare Pipeline - Credential Setup")
    print("="*60)
    print("\nBefore proceeding, get your credentials from AWS Console:")
    print("1. Go to AWS Management Console → IAM → Users → Your User")
    print("2. Click 'Security credentials' tab")
    print("3. Under 'Access keys', click 'Create access key'")
    print("4. Select 'Command Line Interface (CLI)'")
    print("5. Copy the Access Key ID and Secret Access Key")
    print("\n" + "="*60 + "\n")
    
    access_key = input("Enter AWS Access Key ID: ").strip()
    secret_key = input("Enter AWS Secret Access Key: ").strip()
    region = input("Enter AWS Region [us-east-1]: ").strip() or "us-east-1"
    
    # Create .env file
    env_content = f"""# AWS Configuration - Generated by setup script
AWS_ACCESS_KEY_ID={access_key}
AWS_SECRET_ACCESS_KEY={secret_key}
AWS_DEFAULT_REGION={region}
STACK_NAME=healthcare-waveform-pipeline
DYNAMODB_TABLE_NAME=WaveformRecords
ATHENA_DATABASE=healthcare_waveforms
ATHENA_WORKGROUP=healthcare-workgroup
"""
    
    env_file = Path(".env")
    env_file.write_text(env_content)
    os.chmod(env_file, 0o600)  # Restrict permissions to owner only
    
    print(f"\n✓ Credentials saved to .env (permissions: 0600)")
    return access_key, secret_key, region


def load_credentials():
    """Load credentials from .env file"""
    load_dotenv(find_dotenv())
    
    access_key = os.getenv("AWS_ACCESS_KEY_ID")
    secret_key = os.getenv("AWS_SECRET_ACCESS_KEY")
    region = os.getenv("AWS_DEFAULT_REGION", "us-east-1")
    
    return access_key, secret_key, region


def validate_aws_connection(access_key, secret_key, region):
    """Test AWS connectivity with provided credentials"""
    try:
        print("\n" + "="*60)
        print("Testing AWS Connection...")
        print("="*60)
        
        # Create STS client to validate credentials
        sts = boto3.client(
            'sts',
            region_name=region,
            aws_access_key_id=access_key,
            aws_secret_access_key=secret_key
        )
        
        # Get account identity
        identity = sts.get_caller_identity()
        
        print(f"✓ AWS Connection Successful!")
        print(f"  Account ID: {identity['Account']}")
        print(f"  User ARN: {identity['Arn']}")
        print(f"  Region: {region}")
        
        return True
        
    except Exception as e:
        print(f"✗ AWS Connection Failed!")
        print(f"  Error: {str(e)}")
        print("\nPossible causes:")
        print("  - Invalid Access Key ID or Secret Access Key")
        print("  - Credentials have expired or been revoked")
        print("  - Incorrect AWS region")
        print("  - Network connectivity issue")
        return False


def check_required_permissions(region):
    """Check if credentials have required permissions"""
    try:
        print("\n" + "="*60)
        print("Checking Required IAM Permissions...")
        print("="*60 + "\n")
        
        iam = boto3.client('iam')
        s3 = boto3.client('s3', region_name=region)
        cloudformation = boto3.client('cloudformation', region_name=region)
        
        required_services = {
            'S3': ['s3:CreateBucket', 's3:ListBucket', 's3:PutObject'],
            'CloudFormation': ['cloudformation:CreateStack', 'cloudformation:DescribeStacks'],
            'DynamoDB': ['dynamodb:CreateTable', 'dynamodb:PutItem'],
        }
        
        print("✓ You have access to: S3, CloudFormation, DynamoDB")
        print("\nNote: Verify you have IAM permissions for:")
        for service, perms in required_services.items():
            print(f"  - {service}: {', '.join(perms)}")
        
        return True
        
    except Exception as e:
        print(f"⚠ Could not fully verify permissions: {str(e)}")
        print("(This is OK - you can still proceed if you have the required roles)")
        return False


def main():
    env_file = Path(".env")
    
    if env_file.exists():
        print(f"\n.env file already exists at {env_file.absolute()}")
        response = input("Do you want to reconfigure? (y/n) [n]: ").strip().lower()
        
        if response != 'y':
            print("Loading existing credentials...")
            access_key, secret_key, region = load_credentials()
        else:
            access_key, secret_key, region = setup_credentials_from_user()
    else:
        access_key, secret_key, region = setup_credentials_from_user()
    
    # Validate connection
    if validate_aws_connection(access_key, secret_key, region):
        check_required_permissions(region)
        
        print("\n" + "="*60)
        print("✓ AWS Configuration Complete!")
        print("="*60)
        print("\nYou can now run:")
        print("  python aws_upload_waveforms.py --help")
        print("  python aws_process_pipeline.py --help")
        print("  python aws_query.py --help")
        return 0
    else:
        print("\n" + "="*60)
        print("✗ Configuration Failed")
        print("="*60)
        print("\nPlease verify your credentials and try again.")
        return 1


if __name__ == "__main__":
    sys.exit(main())
