#!/usr/bin/env python3
"""
MIMIC-IV Data Verification & Configuration Script
Checks if MIMIC-IV data is downloaded and properly structured for the project
"""

import os
import sys
from pathlib import Path
import argparse

def check_mimic_structure(data_path: str) -> dict:
    """Verify MIMIC-IV directory structure."""
    data_root = Path(data_path)
    
    results = {
        'exists': data_root.exists(),
        'hosp_exists': False,
        'hosp_files': {},
        'waveforms_exists': False,
        'waveforms_count': 0,
    }
    
    if not results['exists']:
        print(f"✗ MIMIC root directory not found: {data_root}")
        return results
    
    print(f"✓ MIMIC root directory found: {data_root}")
    
    # Check hosp module
    hosp_dir = data_root / 'hosp'
    if hosp_dir.exists():
        results['hosp_exists'] = True
        required_files = [
            'admissions.csv.gz',
            'diagnoses_icd.csv.gz',
            'd_icd_diagnoses.csv.gz',
            'labevents.csv.gz',
            'd_labitems.csv.gz',
        ]
        
        print("\n[MIMIC-IV HOSP MODULE]")
        for fname in required_files:
            fpath = hosp_dir / fname
            exists = fpath.exists()
            results['hosp_files'][fname] = exists
            status = "✓" if exists else "✗"
            size = f" ({fpath.stat().st_size / (1024**3):.2f} GB)" if exists else ""
            print(f"  {status} {fname}{size}")
    else:
        print(f"\n✗ hosp/ directory not found at {hosp_dir}")
    
    # Check waveforms
    waveforms_dir = data_root / 'icu' / 'waveforms'
    if waveforms_dir.exists():
        results['waveforms_exists'] = True
        waveform_files = list(waveforms_dir.glob('**/*.dat'))
        results['waveforms_count'] = len(waveform_files)
        print(f"\n[WAVEFORMS]")
        print(f"  ✓ Waveforms directory found at {waveforms_dir}")
        print(f"  Found {results['waveforms_count']} waveform files")
    else:
        print(f"\n⚠ Waveforms directory not found at {waveforms_dir} (optional)")
    
    return results


def generate_config(source_path: str, project_root: str):
    """Generate configuration file pointing to MIMIC data."""
    config_content = f"""#!/usr/bin/env python3
# MIMIC-IV Data Configuration
# Auto-generated by verify_mimic_data.py

# Path to MIMIC-IV root directory
MIMIC_ROOT = "{source_path}"

# Subdirectories
MIMIC_HOSP = MIMIC_ROOT + "/hosp"
MIMIC_WAVEFORMS = MIMIC_ROOT + "/icu/waveforms"

# Feature extraction output
FEATURE_OUTPUT_DIR = "{project_root}/results"
"""
    
    config_path = Path(project_root) / "mimic_config.py"
    config_path.write_text(config_content)
    print(f"\n✓ Configuration file created: {config_path}")
    return config_path


def main():
    parser = argparse.ArgumentParser(
        description="Verify MIMIC-IV data structure and configure project"
    )
    parser.add_argument(
        "--mimic-path",
        required=True,
        help="Path to MIMIC-IV root directory (e.g., /home/manoov/Github/autoencoder-healthcare/data)"
    )
    parser.add_argument(
        "--project-root",
        default="/home/manoov/Github/aws-healthcare-pipeline",
        help="Path to aws-healthcare-pipeline project root"
    )
    
    args = parser.parse_args()
    
    print("="*70)
    print("MIMIC-IV Data Verification & Configuration")
    print("="*70)
    
    # Check structure
    results = check_mimic_structure(args.mimic_path)
    
    # Summary
    print("\n" + "="*70)
    print("SUMMARY")
    print("="*70)
    
    if not results['hosp_exists']:
        print("\n✗ ERROR: MIMIC-IV hosp module not found!")
        print("  The project requires the MIMIC-IV hosp module to run.")
        print(f"  Expected location: {Path(args.mimic_path) / 'hosp'}")
        return 1
    
    hosp_complete = all(results['hosp_files'].values())
    if not hosp_complete:
        print("\n⚠ WARNING: Some hosp files are missing:")
        for fname, exists in results['hosp_files'].items():
            if not exists:
                print(f"    - {fname}")
    else:
        print("\n✓ MIMIC-IV hosp module is complete!")
    
    if results['waveforms_count'] > 0:
        print(f"✓ Waveforms available: {results['waveforms_count']} files")
        print("  (Advanced physiological feature extraction will be enabled)")
    else:
        print("⚠ No waveforms found")
        print("  (Project can run with structured data only)")
    
    # Generate config
    generate_config(args.mimic_path, args.project_root)
    
    print("\n" + "="*70)
    print("NEXT STEPS")
    print("="*70)
    print("\n1. Run feature extraction:")
    print(f"   python examples_feature_extraction.py \\")
    print(f"     --mimic-root {args.mimic_path} \\")
    if results['waveforms_count'] > 0:
        print(f"     --waveform-root {args.mimic_path}/icu/waveforms \\")
    else:
        print(f"     --skip-waveforms \\")
    print(f"     --output-dir ./results")
    
    print("\n2. Check results:")
    print("   ls -lh results/")
    
    return 0


if __name__ == "__main__":
    sys.exit(main())
